name: beyond
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  mobx: ^0.3.9+1
  flutter_mobx: ^0.3.3+1
  flutter_svg: ^0.14.4
  shared_preferences: ^0.5.4+3
  geolocator: ^5.1.5
  shimmer: ^1.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.8.0+1
  mobx_codegen: ^0.3.10
  build_runner: ^1.7.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true