name: beyond
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.2
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.18.1
  shared_preferences: ^0.5.12+4
  geolocator: ^6.1.13
  shimmer: ^1.1.2
  package_info: ^0.4.3+2
  beyond_helpers:
    path: ../beyond_helpers/
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.2
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.9
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true