name: beyond
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  flutter_svg: 0.21.0-nullsafety.0
  shared_preferences: ^2.0.5
  geolocator: ^7.0.1
  shimmer: 2.0.0-nullsafety.0
  package_info: ^2.0.0
  equatable: ^2.0.0
  beyond_helpers:
    path: ../beyond_helpers/
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.0
  mobx_codegen: ^2.0.0
  build_runner: ^1.12.2
  mockito: ^5.0.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true