name: beyond
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  flutter_svg: ^0.15.0
  shared_preferences: ^0.5.6
  geolocator: ^5.2.0
  shimmer: ^1.0.1
  package_info: ^0.4.0+13
  pedantic: ^1.8.0+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen: ^0.4.0+1
  build_runner: ^1.7.3
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true