name: beyond_helpers
description: Utilities for implementing beyond architecture patterns
version: 2.0.0-nullsafety.0
homepage: https://github.com/MisterJimson/beyond
repository: https://github.com/MisterJimson/beyond

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  mobx: ^2.0.0-nullsafety.2
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  flutter_mobx: ^2.0.0-nullsafety.0
  flutter_test:
    sdk: flutter

flutter: