name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.7'
      - run: cd beyond
      - run: flutter pub get
      - run: flutter test
      - run: cd ..
      - run: cd beyond_helpers
      - run: flutter pub get
      - run: flutter test